/**
 * Metas whose elements the public API does not give, or gives wrongly: the achievements that count towards each
 * are fixed DATA taken from the official wiki, like `leyspring-set.ts`. The plugin never requests the wiki
 * (`docs/PLATFORM_POLICY.md`); a set is only a list of ids that the «Logros» section reads as the elements of
 * the followed meta (`tracked-achievements-model.ts`), with the same checks, links and progress as the
 * elements of a category. A meta with a known set uses it before the category rule.
 *
 * GENERATED by `scripts/generate-known-achievement-sets.mjs` (do not edit by hand; regenerate). Source: the
 * `objectives` of the row of each meta on the achievement pages of https://wiki.guildwars2.com/ (`?action=raw`,
 * read on 2026-10-10), each line crossed with `/v2/achievements` (en) by its `#achievement<id>` anchor or, when the
 * line is only a name, by that name on the same page. 209 metas have `CategoryDisplay` and no bits:
 * 107 are here (the wiki's list differs from the API category's, or the API has no category), 62
 * need nothing (the wiki's list is the category's), 40 the wiki does not settle (the category rule applies).
 * A wiki id the API does not serve is replaced by the API's achievement of the same name (e.g. «Return to Siren's
 * Landing»: the wiki says 9991, the API serves 5748); when no name matches it is kept by id (12 ids: hidden,
 * retired or not yet published achievements).
 */

export interface KnownAchievementSet {
	/** The meta achievement. */
	readonly meta: number;
	/** The meta's name in the API (en). */
	readonly name: string;
	/** The meta's last tier: what its bar counts up to. */
	readonly tierMax: number;
	/** The wiki says «Complete all N» with N equal to the bar: the set is exactly what the bar counts. */
	readonly wikiAll: boolean;
	/** The achievements that count, in the wiki's order. */
	readonly members: readonly number[];
}

export const KNOWN_ACHIEVEMENT_SETS: readonly KnownAchievementSet[] = [
	{
		meta: 6202, name: 'End of Dragons: Act 4 Mastery', tierMax: 13, wikiAll: false,
		members: [
			6280, 6156, 6355, 6130, 6114, 6491, 6500, 6251, 6361, 6125, 6225, 6329,
			6081, 6400, 6120, 6174,
		],
	},
	{
		meta: 5790, name: 'Seasons of the Dragons', tierMax: 24, wikiAll: true,
		members: [
			5773, 5804, 5829, 5758, 5742, 5743, 5779, 5756, 5751, 5748, 5948, 5884,
			6005, 5901, 6023, 5995, 5888, 5991, 6024, 5886, 5869, 5926, 5861, 5960,
		],
	},
	{
		meta: 8762, name: 'Kinfall Fractal', tierMax: 4, wikiAll: false,
		members: [
			8783, 8707, 8765, 8711,
		],
	},
	{
		meta: 6162, name: 'Echovald Wilds Mastery', tierMax: 30, wikiAll: false,
		members: [
			6285, 6312, 6183, 6309, 6367, 6193, 6343, 6421, 6325, 6349, 6383, 6386,
			6137, 6372, 6298, 6274, 6187, 6502, 6315, 6207, 6445, 6306, 6458, 6072,
			6097, 6159, 6166, 6138, 6498, 6229, 6451, 6378, 6154, 6221, 6078, 6203,
			6194, 6472, 6305, 6913, 6917, 6897, 6918,
		],
	},
	{
		meta: 6428, name: 'New Kaineng City Mastery', tierMax: 16, wikiAll: false,
		members: [
			6396, 6132, 6512, 6482, 6117, 6151, 6282, 6398, 6461, 6147, 6189, 6399,
			6196, 6432, 6487, 6347, 6242, 6370, 6358, 6381, 6299, 6905, 6929, 6923,
			6914,
		],
	},
	{
		meta: 4651, name: '(Annual) Super Adventure Box Nostalgia', tierMax: 6, wikiAll: false,
		members: [
			4154, 4153, 4158, 4151, 4152, 4160, 7941, 7942, 4156,
		],
	},
	{
		meta: 8582, name: 'Mistburned Barrens Mastery', tierMax: 17, wikiAll: false,
		members: [
			8592, 8638, 8566, 8577, 8585, 8624, 8569, 8620, 8595, 8555, 8593, 8591,
			8623, 8574, 8562, 8579, 8637, 8640, 8634, 8564, 8610, 8552, 8584,
		],
	},
	{
		meta: 8769, name: 'Bava Nisos Mastery', tierMax: 10, wikiAll: false,
		members: [
			8752, 8785, 8718, 8740, 8706, 8755, 8721, 8767, 8708, 8713, 8735, 8781,
			8705, 8747, 8751,
		],
	},
	{
		meta: 3575, name: 'Justice of the Blade', tierMax: 6, wikiAll: false,
		members: [
			3844, 3005, 2999, 3018, 3015, 3020,
		],
	},
	{
		meta: 6901, name: 'What Lies Within', tierMax: 20, wikiAll: false,
		members: [
			6911, 6921, 6931, 6899, 6896, 5711, 6930, 6915, 6876, 6868, 6898, 6895,
			6919, 5292, 6904, 5250, 6856, 6910, 6916, 6909, 6926, 6902, 6932, 5495,
			6908, 6912, 5686, 6903, 6863, 6847, 6875, 6865, 6860,
		],
	},
	{
		meta: 1566, name: 'WvW Spring Tournament 2014 Veteran', tierMax: 10, wikiAll: false,
		members: [
			1538, 1543, 1554, 1544, 1546, 1547, 1548, 1556, 1545, 1549, 1550, 1552,
			1541, 1555, 1553, 1542, 1539,
		],
	},
	{
		meta: 6991, name: 'Amnytas Mastery', tierMax: 14, wikiAll: false,
		members: [
			6972, 6974, 7208, 7176, 7035, 7222, 7102, 7106, 7034, 7041, 7008, 7039,
			7195, 7229, 7630, 7622, 7633, 7624, 7611, 7131, 8011, 8073, 8059, 8046,
			8099,
		],
	},
	{
		meta: 9219, name: 'Return to Janthir Wilds', tierMax: 9, wikiAll: false,
		members: [
			9207, 9213, 9212, 9224, 9228, 9209, 9206, 9203, 9210, 9211, 9204, 9220,
			9205, 9215,
		],
	},
	{
		meta: 4359, name: '"A Star to Guide Us" Mastery', tierMax: 38, wikiAll: false,
		members: [
			4342, 4346, 4392, 4372, 4358, 4347, 4378, 4424, 4389, 4401, 4384, 4369,
			4400, 4393, 4365, 4343, 4370, 4353, 4428, 4418, 4360, 4381, 4414, 4377,
			4430, 4349, 4363, 4427, 4434, 4413, 4421, 4371, 4425, 4390, 4394, 4352,
			4350, 4385, 4403, 4417, 4351, 4375, 4374, 4373, 4366, 4387, 4419, 4348,
			4433, 4426, 4398, 4406, 4376, 4362,
		],
	},
	{
		meta: 7909, name: 'Return to Season 2', tierMax: 8, wikiAll: false,
		members: [
			7918, 7913, 7931, 7900, 7922, 7903, 7865, 7902, 7866, 7892,
		],
	},
	{
		meta: 6873, name: 'The Jade Crisis', tierMax: 18, wikiAll: false,
		members: [
			6116, 6071, 6864, 6879, 6869, 6872, 6861, 6870, 6853, 6849, 6854, 6880,
			6850, 6316, 6855, 6877, 6103, 6423, 6867, 6368, 6845, 6871,
		],
	},
	{
		meta: 1760, name: 'WvW Fall Tournament 2014 Veteran', tierMax: 4, wikiAll: false,
		members: [
			1755, 1757, 1756, 1759,
		],
	},
	{
		meta: 9354, name: 'Visions of Eternity: Code of Creation Mastery', tierMax: 25, wikiAll: false,
		members: [
			9292, 9418, 9469, 9375, 9463, 9350, 9471, 9419, 9380, 9461, 9429, 9353,
			9386, 9458, 9411, 9451, 9421, 9403, 9445, 9371, 9400, 9365, 9358, 9432,
			9395,
		],
	},
	{
		meta: 7856, name: 'Return to Heart of Thorns', tierMax: 8, wikiAll: false,
		members: [
			7879, 7889, 7863, 7860, 7901, 7896, 7933, 7854, 7871, 7867, 7874, 7859,
			7881,
		],
	},
	{
		meta: 8679, name: 'Return to End of Dragons', tierMax: 10, wikiAll: false,
		members: [
			8691, 8667, 8680, 8674, 8675, 8693, 8697, 8673, 8684, 8687, 8689, 8695,
			8700, 8683, 8681,
		],
	},
	{
		meta: 8660, name: 'Commander of Fools', tierMax: 6, wikiAll: false,
		members: [
			8659, 9231, 8656, 8647, 8652, 8655, 8658, 8653, 8648, 8650,
		],
	},
	{
		meta: 5116, name: 'Drakkar, the Ice Dragon\'s Champion', tierMax: 8, wikiAll: false,
		members: [
			5098, 5139, 5103, 5121, 5104, 5127, 5087, 5122, 5148, 5142,
		],
	},
	{
		meta: 6564, name: 'Sky Pirates Mastery', tierMax: 15, wikiAll: false,
		members: [
			6574, 6570, 6569, 6577, 6559, 6566, 6568, 6572, 6565, 6560, 6556, 6567,
			6563, 6557, 6561, 6810,
		],
	},
	{
		meta: 8521, name: 'Return to the Icebrood Saga', tierMax: 10, wikiAll: false,
		members: [
			8517, 8520, 8524, 8530, 8534, 8525, 8526, 8522, 8527, 8518, 8519, 8523,
			8535, 8539, 8528, 8540, 8532, 8531,
		],
	},
	{
		meta: 6784, name: 'Battle for Lion\'s Arch Mastery', tierMax: 18, wikiAll: false,
		members: [
			6805, 6785, 6808, 6781, 6782, 6786, 6783, 6793, 6812, 6799, 6800, 6795,
			6796, 6777, 6794, 6792, 6801, 6791, 6802, 6787, 6789,
		],
	},
	{
		meta: 6504, name: 'End of Dragons: Act 2 Mastery', tierMax: 13, wikiAll: false,
		members: [
			6323, 6288, 6254, 6345, 6245, 6259, 6454, 6425, 6089, 6101, 6419, 6123,
			6173, 6275,
		],
	},
	{
		meta: 8826, name: 'Incursive Investigation', tierMax: 5, wikiAll: false,
		members: [
			8830, 8823, 8840, 8841, 8835,
		],
	},
	{
		meta: 8019, name: 'Secrets of the Obscure: The Midnight King Mastery', tierMax: 16, wikiAll: false,
		members: [
			8021, 7984, 8024, 8043, 7971, 8088, 8012, 8076, 8047, 7966, 7955, 8061,
			8097, 8062, 8010, 7965, 7945, 8148,
		],
	},
	{
		meta: 8275, name: 'Lowland Shore Mastery', tierMax: 30, wikiAll: false,
		members: [
			8197, 8297, 8213, 8158, 8300, 8242, 8183, 8314, 8318, 8222, 8206, 8302,
			8306, 8263, 8288, 8332, 8207, 8286, 8323, 8152, 8173, 8218, 8360, 8291,
			8293, 8192, 8194, 8319, 8170, 8327, 8358, 8333, 8313, 8282, 8188, 8301,
			8303, 8342, 8159, 8362, 8167, 8253, 8250, 8340, 8292, 8309, 8266, 8153,
		],
	},
	{
		meta: 4689, name: '"War Eternal" Mastery', tierMax: 18, wikiAll: true,
		members: [
			4673, 4753, 4744, 4700, 4747, 4740, 4723, 4715, 4669, 4731, 4721, 4697,
			4687, 4708, 4722, 4663, 4737, 4705,
		],
	},
	{
		meta: 6584, name: 'Adventure Guide: Volume Five', tierMax: 12, wikiAll: false,
		members: [
			6656, 6616, 6627, 6651, 6624, 6589, 6681, 6654, 6629, 6649, 6587, 6591,
			6661, 6645,
		],
	},
	{
		meta: 8880, name: 'Shipwreck Strand Mastery', tierMax: 36, wikiAll: false,
		members: [
			8998, 9058, 8921, 8860, 9020, 8983, 8957, 9054, 9001, 9021, 8961, 8854,
			9016, 9046, 8875, 8968, 9059, 8971, 8951, 8992, 8963, 9010, 9032, 8898,
			8914, 9071, 8964, 9051, 9037, 9011, 8935, 8873, 8893, 8926, 9082, 8950,
			8991, 8861, 8981, 8894, 9081, 8934, 8882, 8953, 9052, 8903, 8989, 9026,
			8995, 8969, 8923, 8932, 8976,
		],
	},
	{
		meta: 6331, name: 'Seitung Province Mastery', tierMax: 16, wikiAll: false,
		members: [
			6198, 6418, 6150, 6088, 6460, 6388, 6069, 6464, 6118, 6314, 6468, 6366,
			6377, 6494, 6394, 6257, 6136, 6231, 6415, 6403, 6925, 6922, 6894, 6843,
		],
	},
	{
		meta: 7800, name: 'Inner Nayos Mastery II', tierMax: 21, wikiAll: false,
		members: [
			7834, 7852, 7822, 7782, 7774, 7811, 7799, 7808, 7807, 7797, 7791, 7835,
			7787, 7778, 7789, 7776, 7846, 7801, 7824, 7816, 7784, 7832, 7806, 7777,
			7793, 7830, 7837, 7847,
		],
	},
	{
		meta: 9417, name: 'Leyspring Hollows Mastery', tierMax: 36, wikiAll: false,
		members: [
			9415, 9392, 9448, 9465, 9397, 9433, 9368, 9470, 9401, 9377, 9393, 9438,
			9372, 9355, 9390, 9431, 9464, 9446, 9360, 9351, 9367, 9442, 9383, 9374,
			9407, 9443, 9468, 9420, 9356, 9424, 9457, 9408, 9466, 9455, 9434, 9378,
			9452, 9425, 9369, 9462, 9430, 9366, 9428, 9441, 9439, 9399,
		],
	},
	{
		meta: 6754, name: 'Tower of Nightmares Mastery', tierMax: 15, wikiAll: false,
		members: [
			6755, 6751, 6750, 6749, 6752, 6758, 6756, 6760, 6764, 6753, 6762, 6759,
			6761, 6747, 6748, 6757, 6779, 6806,
		],
	},
	{
		meta: 7017, name: 'Skywatch Archipelago Mastery', tierMax: 22, wikiAll: false,
		members: [
			7218, 7081, 7095, 7079, 7159, 7027, 7038, 7185, 6975, 7230, 7196, 7029,
			7070, 7204, 7220, 7140, 6987, 7021, 7065, 6970, 7100, 7001, 7239, 7055,
			7248, 7092, 7202, 7136, 7013, 7379,
		],
	},
	{
		meta: 9265, name: 'Eternity\'s Garden Mastery', tierMax: 36, wikiAll: false,
		members: [
			9311, 9287, 9254, 9285, 9250, 9329, 9302, 9306, 9325, 9251, 9324, 9295,
			9322, 9273, 9257, 9309, 9338, 9247, 9245, 9259, 9328, 9307, 9255, 9264,
			9298, 9315, 9248, 9281, 9341, 9314, 9296, 9252, 9289, 9270, 9249, 9297,
			9294, 9337, 9321, 9242, 9304, 9277, 9258, 9243, 9343, 9280,
		],
	},
	{
		meta: 3442, name: '"Flashpoint" Mastery', tierMax: 20, wikiAll: false,
		members: [
			3423, 3428, 3398, 3437, 3410, 3407, 3421, 3424, 3412, 3395, 3435, 3401,
			3446, 3396, 3422, 3433, 3406, 3441, 3403, 3439, 3405, 3420, 3427, 3430,
			3408, 3400, 3429, 3402, 3445, 3447, 3436, 3440,
		],
	},
	{
		meta: 696, name: 'Bazaar Ambassador', tierMax: 16, wikiAll: false,
		members: [
			709, 700, 698, 710, 711, 701, 703, 708, 707, 706, 704, 705,
			697, 702, 699, 720, 712, 713, 714, 715, 716, 717, 719,
		],
	},
	{
		meta: 4093, name: '"A Bug in the System" Mastery', tierMax: 35, wikiAll: false,
		members: [
			4146, 4115, 4092, 4091, 4098, 4148, 4133, 4105, 4121, 4136, 4143, 4095,
			4124, 4147, 4135, 4139, 4114, 4122, 4149, 4142, 4132, 4127, 4100, 4117,
			4130, 4126, 4137, 4120, 4140, 4145, 4101, 4119, 4110, 4129, 4090, 4131,
			4102, 4144, 4106, 4112, 4103, 4141, 4108, 4125, 4096, 4134, 4150,
		],
	},
	{
		meta: 4940, name: '"Bound by Blood" Mastery', tierMax: 54, wikiAll: false,
		members: [
			4949, 4972, 4908, 4959, 4941, 4939, 4944, 4993, 4912, 4956, 4962, 4967,
			4960, 4911, 4942, 4921, 4950, 4986, 4905, 4929, 4931, 4975, 4981, 4964,
			4932, 4989, 4995, 4901, 4917, 4926, 4951, 4914, 4971, 4991, 4903, 4935,
			4982, 4922, 4919, 4970, 4948, 4920, 4990, 4910, 4946, 4988, 4965, 4992,
			4957, 4979, 4938, 4978, 4933, 4902, 4983, 4987, 4974, 4899, 4915, 4936,
			4963, 4985, 4923, 4916, 4961, 4925, 4900, 4966, 4955, 4973, 4947, 4928,
		],
	},
	{
		meta: 3123, name: '"Rising Flames" Mastery', tierMax: 23, wikiAll: false,
		members: [
			3137, 3129, 3113, 3139, 3124, 3148, 3120, 3126, 3121, 3110, 3104, 3128,
			3133, 3119, 3127, 3131, 3150, 3145, 3105, 3138, 3130, 3115, 3107, 3136,
			3112, 3134, 3142, 3147, 3122, 3109,
		],
	},
	{
		meta: 3348, name: '"The Head of the Snake" Mastery', tierMax: 28, wikiAll: false,
		members: [
			3294, 3285, 3301, 3372, 3317, 3340, 3333, 3343, 3282, 3286, 3351, 3365,
			3306, 3361, 3311, 3323, 3326, 3379, 3344, 3322, 3367, 3288, 3320, 3315,
			3314, 3329, 3330, 3338, 3380, 3354, 3309, 3381, 3374, 3308, 3377, 3350,
			3358, 3284, 3383,
		],
	},
	{
		meta: 863, name: 'Minor in Achievement', tierMax: 15, wikiAll: false,
		members: [
			556, 552, 557, 553, 548, 558, 554, 560, 549, 550, 547, 551,
			546, 559, 555, 2865,
		],
	},
	{
		meta: 6952, name: 'Silent Surf Fractal', tierMax: 7, wikiAll: false,
		members: [
			6944, 6947, 6948, 6940, 6934, 6937, 6942,
		],
	},
	{
		meta: 1827, name: '"Seeds of Truth" Mastery', tierMax: 6, wikiAll: true,
		members: [
			1831, 1833, 1832, 1829, 1830, 1828,
		],
	},
	{
		meta: 3516, name: '"One Path Ends" Mastery', tierMax: 36, wikiAll: false,
		members: [
			3537, 3493, 3533, 3503, 3454, 3456, 3524, 3507, 3485, 3511, 3472, 3470,
			3462, 3467, 3484, 3510, 3517, 3497, 3498, 3546, 3486, 3460, 3502, 3496,
			3521, 3480, 3519, 3473, 3548, 3482, 3520, 3518, 3542, 3527, 3536, 3481,
			3487, 3506, 3490, 3475, 3508, 3477,
		],
	},
	{
		meta: 6539, name: 'Flame and Frost Mastery', tierMax: 12, wikiAll: false,
		members: [
			6533, 6553, 6538, 6529, 6536, 6547, 6535, 6554, 6528, 6548, 6531, 6524,
			6780,
		],
	},
	{
		meta: 1795, name: '"Entanglement" Mastery', tierMax: 9, wikiAll: true,
		members: [
			1666, 1661, 1667, 1663, 1664, 1665, 1657, 1662, 1660,
		],
	},
	{
		meta: 4472, name: 'Rolling Racer', tierMax: 10, wikiAll: false,
		members: [
			4473, 4470, 4469, 4464, 4463, 4467, 4477, 4462, 4471, 4466,
		],
	},
	{
		meta: 8612, name: 'Godsbane', tierMax: 14, wikiAll: false,
		members: [
			8454, 8485, 8472, 8461, 8502, 8631, 8580, 8639, 8581, 8609, 8601, 8603,
			8548, 8583,
		],
	},
	{
		meta: 4865, name: '(Annual) Four Winds Customs', tierMax: 18, wikiAll: false,
		members: [
			4879, 4863, 4861, 4873, 8787, 4882, 4878, 4868, 4864, 4871, 4881, 4869,
			4877, 4874, 4875, 4870, 4880, 4860, 4867, 4866, 4862, 4872, 4883,
		],
	},
	{
		meta: 1784, name: '"The Dragon\'s Reach, Part 1" Mastery', tierMax: 6, wikiAll: true,
		members: [
			1678, 1677, 1668, 1673, 1672, 1671,
		],
	},
	{
		meta: 9352, name: 'Solitary Throne Fractal', tierMax: 5, wikiAll: false,
		members: [
			9449, 9444, 9357, 9459, 9453,
		],
	},
	{
		meta: 3513, name: 'Shattered Observatory Fractal', tierMax: 6, wikiAll: false,
		members: [
			3455, 3474, 3528, 3457, 3494, 3540,
		],
	},
	{
		meta: 4490, name: '(Annual) Wintersday Traditions', tierMax: 7, wikiAll: false,
		members: [
			4045, 4048, 4051, 4059, 4055, 4052, 4046, 4043,
		],
	},
	{
		meta: 1785, name: '"Echoes of the Past" Mastery', tierMax: 7, wikiAll: true,
		members: [
			1787, 1789, 1786, 1793, 1792, 1788, 1791,
		],
	},
	{
		meta: 8091, name: 'Inner Nayos Mastery III', tierMax: 23, wikiAll: false,
		members: [
			7968, 8023, 7972, 8041, 7981, 8038, 8071, 7999, 8009, 8098, 7987, 7980,
			8045, 8069, 8054, 8008, 8082, 8001, 8022, 8036, 8095, 7996, 8031, 7990,
			8081, 8090, 7998, 7995, 8034, 8096, 7973, 7948,
		],
	},
	{
		meta: 1796, name: '"Gates of Maguuma" Mastery', tierMax: 9, wikiAll: true,
		members: [
			1646, 1650, 1649, 1640, 1642, 1643, 1644, 1648, 1647,
		],
	},
	{
		meta: 4544, name: '"All or Nothing" Mastery', tierMax: 30, wikiAll: false,
		members: [
			4538, 4550, 4569, 4586, 4493, 4576, 4594, 4617, 4513, 4497, 4588, 4618,
			4567, 4510, 4553, 4605, 4591, 4499, 4596, 4522, 4516, 4507, 4564, 4590,
			4498, 4604, 4621, 4559, 4616, 4600, 4515, 4545, 4579, 4601, 4577, 4506,
			4503, 4532, 4539,
		],
	},
	{
		meta: 8140, name: 'Return to Season 3', tierMax: 14, wikiAll: false,
		members: [
			8120, 8138, 8146, 8133, 8134, 8143, 8147, 8149, 8112, 8121, 8144, 8119,
			8130, 8141, 8131, 8110, 8126, 8124, 8136,
		],
	},
	{
		meta: 2314, name: 'Heart of Thorns Act I Mastery', tierMax: 18, wikiAll: true,
		members: [
			2185, 2264, 2440, 2315, 2178, 2201, 2361, 2469, 2587, 2254, 2616, 2287,
			2174, 2632, 2219, 2639, 2301, 2466,
		],
	},
	{
		meta: 8421, name: 'Return to Path of Fire', tierMax: 8, wikiAll: false,
		members: [
			8395, 8394, 8417, 8426, 8424, 8384, 8376, 8389, 8406, 8382, 8397, 8416,
		],
	},
	{
		meta: 8626, name: 'Janthir Wilds: Repentance Mastery', tierMax: 12, wikiAll: false,
		members: [
			8614, 8632, 8559, 8600, 8573, 8618, 8542, 8570, 8558, 8629, 8613, 8561,
		],
	},
	{
		meta: 4274, name: 'Master of the Four Winds', tierMax: 25, wikiAll: false,
		members: [
			4312, 4322, 4321, 4276, 4292, 4316, 4277, 4297, 4302, 4303, 4304, 4305,
			4288, 4334, 4330, 4310, 4286, 4278, 4323, 4285, 4294, 4327, 4324, 4325,
			4329,
		],
	},
	{
		meta: 990, name: 'Premier Season Veteran', tierMax: 15, wikiAll: false,
		members: [
			979, 981, 973, 980, 984, 975, 971, 983, 969, 970, 976, 972,
			982, 974, 8718, 977, 987, 986, 985,
		],
	},
	{
		meta: 4815, name: '(Annual) Dragon Bash Feats', tierMax: 7, wikiAll: false,
		members: [
			4850, 4846, 4837, 4836, 4841, 4838, 4813, 4832, 4820,
		],
	},
	{
		meta: 1790, name: '"The Dragon\'s Reach, Part 2" Mastery', tierMax: 9, wikiAll: true,
		members: [
			1705, 1704, 1706, 1701, 1703, 1702, 1699, 1698, 1691,
		],
	},
	{
		meta: 4625, name: '(Annual) Lunar New Year Customs', tierMax: 5, wikiAll: false,
		members: [
			4087, 4083, 4067, 4075, 4080, 4081,
		],
	},
	{
		meta: 5401, name: '"Jormag Rising" Mastery', tierMax: 32, wikiAll: false,
		members: [
			5380, 5353, 5379, 5417, 5366, 5415, 5421, 5374, 5378, 5396, 5413, 5348,
			5376, 5387, 5357, 5369, 5351, 5419, 5394, 5423, 5403, 5364, 5359, 5362,
			5386, 5410, 5424, 5414, 5363, 5420, 5409, 5429, 5389, 5352, 5381, 5365,
			5358, 5405, 5361, 5367,
		],
	},
	{
		meta: 4816, name: 'The Dragon Bash Experience', tierMax: 7, wikiAll: false,
		members: [
			4822, 4823, 4828, 4848, 4821, 4849, 4834, 4814, 4840, 4829,
		],
	},
	{
		meta: 8717, name: 'Janthir Wilds: Absolution Mastery', tierMax: 12, wikiAll: false,
		members: [
			8726, 8758, 8731, 8757, 8728, 8716, 8759, 8764, 8712, 8760, 8727, 8746,
			8775,
		],
	},
	{
		meta: 5291, name: '"No Quarter" Mastery', tierMax: 17, wikiAll: false,
		members: [
			5318, 5245, 5313, 5268, 5262, 5248, 5306, 5316, 5329, 5275, 5285, 5327,
			5312, 5319, 5298, 5308, 5297, 5331, 5252, 5325, 5284, 5271, 5247, 5474,
			5500,
		],
	},
	{
		meta: 7026, name: 'Master of the Rifts', tierMax: 18, wikiAll: false,
		members: [
			7184, 7167, 7228, 7012, 7133, 7194, 7237, 7002, 6986, 7007, 7142, 7080,
			7094, 7020, 6998, 7004, 7235, 7123, 7601, 7637, 7615, 7632, 7635, 7629,
			7681, 7723, 7667, 7727, 7674, 7661, 7697, 7700, 7729,
		],
	},
	{
		meta: 4642, name: 'Warclaw Companion', tierMax: 8, wikiAll: false,
		members: [
			4634, 4649, 4636, 4646, 4628, 4643, 4640, 4629,
		],
	},
	{
		meta: 9057, name: 'Starlit Weald Mastery', tierMax: 36, wikiAll: false,
		members: [
			8904, 9049, 9027, 9040, 9039, 8884, 8919, 9022, 9048, 8967, 9045, 9069,
			9062, 9000, 8909, 9074, 9078, 8986, 9061, 8867, 8922, 9077, 8902, 8933,
			9044, 8918, 9007, 9083, 8866, 9072, 9033, 8938, 8856, 8917, 8862, 8937,
			8996, 8886, 8982, 8920, 9047, 9025, 9018, 9035, 9003, 9042, 8941, 8942,
			8881, 8857, 9065, 8915, 9028, 8952, 9008,
		],
	},
	{
		meta: 8042, name: 'Lonely Tower Fractal', tierMax: 5, wikiAll: false,
		members: [
			8067, 8044, 8051, 7946, 8005,
		],
	},
	{
		meta: 2738, name: 'Path of the Ascension I: The Thrill of Battle', tierMax: 11, wikiAll: true,
		members: [
			2690, 2707, 2709, 2758, 2677, 2698, 2672, 2750, 2737, 2689, 2759,
		],
	},
	{
		meta: 5706, name: '"Champions" Mastery', tierMax: 24, wikiAll: false,
		members: [
			5518, 5544, 5546, 5503, 5539, 5512, 5478, 5485, 5515, 5650, 5642, 5640,
			5698, 5709, 5700, 5693, 5703, 5697, 5708, 5691, 5688, 5704, 5658, 5644,
			5622, 5663, 5659, 5666, 5633, 5647, 5616, 5626, 5632, 5637, 5643, 5545,
			5575, 5667, 5652, 5651,
		],
	},
	{
		meta: 170, name: 'Kegmaster', tierMax: 7, wikiAll: false,
		members: [
			164, 171, 169, 168, 166, 167, 165,
		],
	},
	{
		meta: 1342, name: 'Triple Trouble', tierMax: 10, wikiAll: false,
		members: [
			1341, 1340, 1338, 1333, 1337, 1336, 1339, 1335, 1332, 1334,
		],
	},
	{
		meta: 9454, name: 'Master of Masteries: Visions of Eternity', tierMax: 8, wikiAll: false,
		members: [
			9063, 8908, 9246, 9354, 8880, 9057, 9265, 9417,
		],
	},
	{
		meta: 1816, name: '"Tangled Paths" Mastery', tierMax: 6, wikiAll: true,
		members: [
			1819, 1821, 1820, 1818, 1815, 1817,
		],
	},
	{
		meta: 8273, name: 'Janthir Syntri Mastery', tierMax: 24, wikiAll: false,
		members: [
			8229, 8256, 8348, 8241, 8164, 8236, 8281, 8234, 8270, 8155, 8334, 8172,
			8203, 8210, 8325, 8237, 8219, 8157, 8227, 8280, 8248, 8193, 8335, 8367,
			8187, 8199, 8289, 8251, 8350, 8357, 8299, 8198, 8196, 8337, 8249, 8175,
			8161, 8205,
		],
	},
	{
		meta: 8908, name: 'Visions of Eternity: Act 2 Mastery', tierMax: 21, wikiAll: false,
		members: [
			9017, 8940, 8955, 9029, 9070, 9043, 8877, 9085, 8871, 8887, 9076, 8907,
			8988, 8931, 9060, 9005, 9023, 8948, 8870, 8897, 8876, 8946,
		],
	},
	{
		meta: 122, name: 'Dungeon Master', tierMax: 8, wikiAll: false,
		members: [
			186, 187, 185, 188, 189, 190, 191, 192,
		],
	},
	{
		meta: 5203, name: 'Steel and Fire Mastery', tierMax: 27, wikiAll: false,
		members: [
			5178, 5181, 5192, 5209, 5234, 5236, 5200, 5205, 5177, 5191, 5206, 5208,
			5237, 5229, 5196, 5185, 5188, 5222, 5227, 5189, 5214, 5212, 5225, 5179,
			5215, 5218, 5186, 5182, 5228, 5217, 5202, 5230, 5211, 5176, 5231, 5224,
			5226,
		],
	},
	{
		meta: 5107, name: '"Shadow in the Ice" Mastery', tierMax: 37, wikiAll: false,
		members: [
			5130, 5109, 5102, 5124, 5113, 5096, 5146, 5112, 5083, 5117, 5093, 5135,
			5133, 5134, 5118, 5091, 5088, 5129, 5090, 5089, 5119, 5131, 5101, 5110,
			5120, 5034, 5092, 5144, 5108, 5136, 5140, 5126, 5029, 5132, 5099, 5095,
			5094, 5143, 5100, 5097, 5137, 5145, 5125, 5123,
		],
	},
	{
		meta: 3900, name: 'Path of Fire: Act 1 Mastery', tierMax: 15, wikiAll: true,
		members: [
			3816, 3808, 3730, 3622, 3648, 3751, 3586, 3606, 3853, 3879, 3813, 3568,
			3811, 3675, 3778,
		],
	},
	{
		meta: 3171, name: '"A Crack in the Ice" Mastery', tierMax: 21, wikiAll: true,
		members: [
			3221, 3191, 3206, 3173, 3212, 3214, 3240, 3174, 3217, 3188, 3179, 3186,
			3231, 3195, 3216, 3193, 3224, 3210, 3227, 3182, 3207,
		],
	},
	{
		meta: 3050, name: '"Out of the Shadows" Mastery', tierMax: 18, wikiAll: false,
		members: [
			3042, 3054, 3056, 3059, 3074, 3065, 3082, 3064, 3077, 3062, 3049, 3081,
			3040, 3070, 3073, 3072, 3053, 3076, 3088,
		],
	},
	{
		meta: 9246, name: 'Visions of Eternity: The Only Way Mastery', tierMax: 19, wikiAll: false,
		members: [
			9278, 9317, 9284, 9312, 9336, 9261, 9272, 9268, 9276, 9301, 9319, 9340,
			9269, 9332, 9275, 9300, 9316, 9326, 9299,
		],
	},
	{
		meta: 4195, name: '"Long Live the Lich" Mastery', tierMax: 38, wikiAll: false,
		members: [
			4236, 4214, 4230, 4201, 4271, 4247, 4238, 4259, 4234, 4246, 4269, 4227,
			4194, 4182, 4198, 4192, 4203, 4216, 4199, 4256, 4262, 4250, 4272, 4208,
			4204, 4264, 4231, 4243, 4217, 4223, 4253, 4209, 4220, 4188, 4213, 4255,
			4228, 4206, 4261, 4258, 4186, 4235, 4207, 4251, 4233, 4265, 4205, 4270,
		],
	},
	{
		meta: 2054, name: '"Point of No Return" Mastery', tierMax: 8, wikiAll: true,
		members: [
			2056, 2055, 2053, 2058, 2057, 2062, 2061, 2059,
		],
	},
	{
		meta: 864, name: 'Major in Achievement', tierMax: 13, wikiAll: false,
		members: [
			866, 867, 865, 868, 869, 870, 875, 873, 876, 874, 877, 878,
			879, 871, 872, 2846,
		],
	},
	{
		meta: 5012, name: 'Whisper in the Dark Mastery', tierMax: 20, wikiAll: false,
		members: [
			5053, 5050, 5063, 5031, 5014, 5044, 5054, 5016, 5010, 5038, 5019, 5040,
			5023, 5027, 5046, 5055, 5018, 5056, 5062, 5030, 5020, 5036, 5051, 5061,
			5052, 5042, 5035,
		],
	},
	{
		meta: 3209, name: 'Nightmare Fractal', tierMax: 7, wikiAll: false,
		members: [
			3211, 3205, 3199, 3236, 3208, 3243, 3218,
		],
	},
	{
		meta: 6667, name: 'Adventure Guide: Volume Three', tierMax: 13, wikiAll: false,
		members: [
			6746, 6618, 6608, 6580, 6639, 6606, 6585, 6715, 6607, 6605, 6630, 6604,
			6675, 6583, 6665,
		],
	},
	{
		meta: 7769, name: 'Return to Season 1', tierMax: 9, wikiAll: false,
		members: [
			7765, 7764, 7770, 7747, 7763, 7751, 7750, 7767, 7748, 7760, 7771, 7758,
			7756, 7768, 7753, 7754,
		],
	},
	{
		meta: 6453, name: 'Dragon\'s End Mastery', tierMax: 25, wikiAll: false,
		members: [
			6303, 6470, 6178, 6300, 6164, 6256, 6228, 6170, 6496, 6127, 6292, 6456,
			6375, 6260, 6160, 6186, 6241, 6140, 6144, 6234, 6236, 6429, 6271, 6217,
			6082, 6148, 6131, 6320, 6266,
		],
	},
	{
		meta: 6401, name: 'End of Dragons: Act 3 Mastery', tierMax: 14, wikiAll: false,
		members: [
			6322, 6255, 6146, 6474, 6208, 6376, 6301, 6252, 6340, 6391, 6452, 6373,
			6444, 6268, 6294, 6278, 6446,
		],
	},
	{
		meta: 5438, name: 'Sunqua Peak Fractal', tierMax: 7, wikiAll: false,
		members: [
			5442, 5445, 5456, 5451, 5450, 5444, 5440,
		],
	},
	{
		meta: 6682, name: 'Clockwork Chaos Mastery', tierMax: 13, wikiAll: false,
		members: [
			6689, 6694, 6684, 6686, 6688, 6690, 6685, 6696, 6687, 6695, 6691, 6693,
			6692, 6809,
		],
	},
	{
		meta: 4439, name: '(Annual) Halloween Rituals', tierMax: 9, wikiAll: false,
		members: [
			4435, 4446, 4449, 4448, 4442, 4452, 4445, 4447, 5006, 4438,
		],
	},
	{
		meta: 8802, name: 'Return to Secrets of the Obscure', tierMax: 9, wikiAll: false,
		members: [
			8786, 8789, 8795, 8803, 8788, 8799, 8792, 8791, 8804, 8805, 8794, 8796,
			8797,
		],
	},
	{
		meta: 3988, name: '"Daybreak" Mastery', tierMax: 30, wikiAll: false,
		members: [
			3962, 3955, 4040, 4009, 3994, 3996, 3997, 3984, 3976, 4002, 4022, 4014,
			3982, 4032, 3986, 3975, 3965, 4039, 3999, 3978, 4027, 4041, 4034, 3959,
			3983, 4023, 3958, 4013, 4007, 3969, 4042, 3985, 3989, 3992, 3960, 4008,
			3995, 3991, 4031, 3968, 4019, 3981, 4029, 4026,
		],
	},
];

const BY_META: ReadonlyMap<number, readonly number[]> = new Map(KNOWN_ACHIEVEMENT_SETS.map((set) => [set.meta, set.members]));

/** The ids that count towards the meta `id`, in the wiki's order; null when there is no known set for it. */
export function knownSetMembersOf(id: number): number[] | null {
	const members = BY_META.get(id);
	return members === undefined ? null : [...members];
}
