import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
Edit the TypeScript sources under src/ instead.
*/
`;

const prod = process.argv[2] === 'production';
const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	// H14.18: the production bundle carried one `console.warn` from the
	// bundled `yaml` package's own deprecation notice. `drop` strips every
	// `console.*` call from the bundled output, not just that one call site,
	// so it also catches any future dependency that logs on its own; it stays
	// off in dev so `npm run dev` keeps normal debugging output.
	drop: prod ? ['console'] : [],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
}

await context.watch();
