/** Localized copy for the shared Hebra/Obsidian inventory observation surface. */
const EN = {
 details: 'Details', notices: 'Observed valuable items', noNotices: 'No notification intents recorded.', receiptLimit: 'Addon acceptance does not confirm that a notice was displayed.', noticeValue: 'Estimated value', noticeState: 'Notification intent', receipt: 'Addon receipt', noReceipt: 'No receipt', notice_awaiting_price: 'Waiting for a price', notice_skipped: 'Skipped', notice_ready: 'Ready', notice_dispatching: 'Dispatch claimed', notice_processed: 'Processed', noticeNoPrice: 'No price', noticeBelowThreshold: 'Below threshold', noticeClosed: 'Session closed', receipt_pending: 'Awaiting receipt', receipt_received: 'Accepted by addon', receipt_unconfirmed: 'Receipt unconfirmed · may not have been displayed', noticeFailed: 'Failed channels',
 history: 'Saved session', current: 'Current session', title: 'Inventory observations', timeline: 'Timeline', summary: 'Session summary',
 source: 'Source', character: 'Character', nexus: 'Local Nexus · character bags', missing: 'No Nexus inventory source',
 warming_up: 'Waiting for baseline', ready: 'Reading available', stale: 'Reading is old',
 unavailable: 'Reading unavailable', conflict: 'Another Nexus source owns this session',
 connected: 'Game connected', disconnected: 'Game disconnected',
 idle: 'No session', starting: 'Preparing session', active: 'Session active', stopping: 'Finishing session',
 complete: 'Session complete', error: 'Session error · recovery required',
 empty: 'No inventory changes observed yet. A baseline is not an acquisition.',
 scope: 'Observed increases and decreases in character bags. Their cause is unknown; changes between samples may be missed.',
 items: 'Item coverage', currencies: 'Currency coverage',
 partial: 'Partial', none: 'No coverage', listed: 'Listed currencies only',
 duration: 'Active duration',
 rate: 'Estimated item subtotal/hour · partial',
 priceBasis: 'Valuation criterion', price: 'Instant sell, net of fees', unpriced: 'Items without a price',
 time: 'Observed at', entity: 'Item / currency', quantity: 'Change', before: 'Before', after: 'After',
 net: 'Net change', value: 'Estimated known net item subtotal',
 previous: 'Previous', next: 'Next', page: 'Page',
 gaps: 'Reading gaps',
 slots: 'Free character bag slots',
 magicFind: 'Magic Find', manual: 'Manual', verified: 'Verified', unknown: 'Unknown',
 last: 'Last committed reading',
 disconnect: 'Connection lost', source_stale: 'No recent reader sample', read_failed: 'Reader could not complete the sample', partial_inventory: 'Some bag positions could not be read', context_changed: 'Character or map changed', host_restart: 'Host restarted', storage_unavailable: 'Could not store the reading', unsupported_build: 'Unsupported game build', source_missing: 'Reader source missing', cursor_gap: 'Missing sample', kindItem: 'Item', kindCurrency: 'Currency',
} as const;
const ES: Record<keyof typeof EN, string> = {
 details: 'Detalles', notices: 'Objetos valiosos observados', noNotices: 'Sin intentos de aviso guardados.', receiptLimit: 'La aceptación del addon no confirma que el aviso se haya mostrado.', noticeValue: 'Valor estimado', noticeState: 'Intento de aviso', receipt: 'Recepción del addon', noReceipt: 'Sin recepción', notice_awaiting_price: 'Esperando precio', notice_skipped: 'Omitido', notice_ready: 'Preparado', notice_dispatching: 'Envío reclamado', notice_processed: 'Procesado', noticeNoPrice: 'Sin precio', noticeBelowThreshold: 'Bajo el umbral', noticeClosed: 'Sesión terminada', receipt_pending: 'Esperando recepción', receipt_received: 'Aceptado por el addon', receipt_unconfirmed: 'Recepción no confirmada · puede no haberse mostrado', noticeFailed: 'Canales fallidos',
 history: 'Sesión guardada', current: 'Sesión actual', title: 'Observaciones del inventario', timeline: 'Cronología', summary: 'Resumen de sesión',
 source: 'Fuente', character: 'Personaje', nexus: 'Nexus local · bolsas del personaje', missing: 'Sin fuente Nexus de inventario',
 warming_up: 'Esperando baseline', ready: 'Lectura disponible', stale: 'Lectura antigua',
 unavailable: 'Lectura no disponible', conflict: 'Otra fuente Nexus posee esta sesión',
 connected: 'Juego conectado', disconnected: 'Juego desconectado',
 idle: 'Sin sesión', starting: 'Preparando sesión', active: 'Sesión activa', stopping: 'Terminando sesión',
 complete: 'Sesión terminada', error: 'Error de sesión · requiere recuperación',
 empty: 'Todavía no se han observado cambios de inventario. Un baseline no es una adquisición.',
 scope: 'Aumentos y disminuciones observados en las bolsas del personaje. Su causa es desconocida; pueden perderse cambios entre muestras.',
 items: 'Cobertura de objetos', currencies: 'Cobertura de monedas',
 partial: 'Parcial', none: 'Sin cobertura', listed: 'Solo monedas enumeradas',
 duration: 'Duración activa',
 rate: 'Subtotal estimado de objetos/h · parcial',
 priceBasis: 'Criterio de valoración', price: 'Venta inmediata, descontadas comisiones', unpriced: 'Objetos sin precio',
 time: 'Observado a las', entity: 'Objeto / moneda', quantity: 'Cambio', before: 'Antes', after: 'Después',
 net: 'Cambio neto', value: 'Subtotal neto estimado de objetos conocidos',
 previous: 'Anterior', next: 'Siguiente', page: 'Página',
 gaps: 'Huecos de lectura',
 slots: 'Huecos libres en las bolsas del personaje',
 magicFind: 'Hallazgo mágico', manual: 'Manual', verified: 'Verificado', unknown: 'Desconocido',
 last: 'Última lectura guardada',
 disconnect: 'Conexión perdida', source_stale: 'Sin muestra reciente del lector', read_failed: 'El lector no pudo completar la muestra', partial_inventory: 'No se pudieron leer algunas posiciones de las bolsas', context_changed: 'Cambio de personaje o mapa', host_restart: 'Host reiniciado', storage_unavailable: 'No se pudo guardar la lectura', unsupported_build: 'Versión del juego no compatible', source_missing: 'Falta la fuente del lector', cursor_gap: 'Falta una muestra', kindItem: 'Objeto', kindCurrency: 'Moneda',
};
/** Copy of the simplified Session tab (6 oct 2026): one header, three figures, one chart, one timeline. */
const SIMPLE_EN = {
 stateIdle: 'No session', stateStarting: 'Preparing session', stateActive: 'In progress', stateStopping: 'Finishing session',
 stateComplete: 'Finished', stateError: 'Session error', stateGameOff: 'Game disconnected',
 start: 'Start session', stop: 'Finish session', startBusy: 'Starting…', stopBusy: 'Finishing…',
 hintReady: 'Game connected. Start a session to see what enters your bags.',
 hintGameOff: 'Open Guild Wars 2 with the Nexus addon to be able to start.',
 hintConsult: 'This installation is in consult mode: it does not run sessions.',
 startFailed: 'The session could not be started', stopFailed: 'The session could not be finished', discardFailed: 'The old session could not be discarded',
 oldSessionBlocks: 'An older session is blocking a new one.',
 oldSessionHint: 'Finish it with the session commands in the command palette.',
 discardOld: 'Discard old session',
 statValue: 'Estimated value', moneySpoken: '{gold} gold, {silver} silver, {copper} copper', moneySpokenLoss: 'minus {gold} gold, {silver} silver, {copper} copper', statRate: 'Per hour', objects: 'Objects', currencies: 'Currencies', coins: 'Observed coins',
 noChanges: 'No inventory changes observed yet.',
 chartTitle: 'Value over time', chartLabel: 'Estimated value from {from} to {to}, {start} to {end}, {gaps}',
 gapsNone: 'no reading gaps', gapsOne: '1 reading gap', gapsMany: '{n} reading gaps',
 legendOne: 'No reading · 1 gap', legendMany: 'No reading · {n} gaps', since: 'since',
 tipFirst: 'first reading', tipChange: '{delta} vs. previous', tipGap: 'no readings from {from} to {to}', tipGapOpen: 'no readings since {from}',
 timeline: 'Timeline', showMore: 'Show 50 more', shownOf: '{shown} of {total}', tileLabel: '{name}, {quantity}',
 previous: 'Previous sessions', previousLoading: 'Loading sessions…', previousEmpty: 'There are no saved sessions yet.',
 previousFailed: 'The saved sessions could not be read.', retry: 'Retry', showMoreSessions: 'Show 10 more',
 objectsOne: '1 object', objectsMany: '{n} objects',
 previousItemsLabel: 'Objects of the session of {when}', moreObjects: '{n} more objects',
} as const;
const SIMPLE_ES: Record<keyof typeof SIMPLE_EN, string> = {
 stateIdle: 'Sin sesión', stateStarting: 'Preparando sesión', stateActive: 'En curso', stateStopping: 'Terminando sesión',
 stateComplete: 'Terminada', stateError: 'Error de sesión', stateGameOff: 'Juego desconectado',
 start: 'Iniciar sesión', stop: 'Terminar sesión', startBusy: 'Iniciando…', stopBusy: 'Terminando…',
 hintReady: 'Juego conectado. Inicia una sesión para ver lo que entra en tus bolsas.',
 hintGameOff: 'Abre Guild Wars 2 con el addon de Nexus para poder iniciar.',
 hintConsult: 'Esta instalación está en modo consulta: no lleva sesiones.',
 startFailed: 'No se pudo iniciar la sesión', stopFailed: 'No se pudo terminar la sesión', discardFailed: 'No se pudo descartar la sesión antigua',
 oldSessionBlocks: 'Una sesión antigua impide abrir otra.',
 oldSessionHint: 'Termínala con los comandos de sesión de la paleta de comandos.',
 discardOld: 'Descartar sesión antigua',
 statValue: 'Valor estimado', moneySpoken: '{gold} de oro, {silver} de plata, {copper} de cobre', moneySpokenLoss: 'menos {gold} de oro, {silver} de plata, {copper} de cobre', statRate: 'Por hora', objects: 'Objetos', currencies: 'Monedas', coins: 'Monedas observadas',
 noChanges: 'Todavía no se han observado cambios de inventario.',
 chartTitle: 'Valor en el tiempo', chartLabel: 'Valor estimado de {from} a {to}, de {start} a {end}, {gaps}',
 gapsNone: 'sin huecos de lectura', gapsOne: '1 hueco de lectura', gapsMany: '{n} huecos de lectura',
 legendOne: 'Sin lectura · 1 hueco', legendMany: 'Sin lectura · {n} huecos', since: 'desde',
 tipFirst: 'primera lectura', tipChange: '{delta} vs. anterior', tipGap: 'sin lecturas de {from} a {to}', tipGapOpen: 'sin lecturas desde {from}',
 timeline: 'Cronología', showMore: 'Ver 50 más', shownOf: '{shown} de {total}', tileLabel: '{name}, {quantity}',
 previous: 'Sesiones anteriores', previousLoading: 'Cargando sesiones…', previousEmpty: 'Todavía no hay sesiones guardadas.',
 previousFailed: 'No se han podido leer las sesiones guardadas.', retry: 'Reintentar', showMoreSessions: 'Ver 10 más',
 objectsOne: '1 objeto', objectsMany: '{n} objetos',
 previousItemsLabel: 'Objetos de la sesión del {when}', moreObjects: '{n} objetos más',
};
export type LiveSessionCopyKey = keyof typeof EN | keyof typeof SIMPLE_EN;
export function liveSessionCopy(locale: 'es' | 'en', key: LiveSessionCopyKey): string {
 if (key in SIMPLE_EN) return (locale === 'es' ? SIMPLE_ES : SIMPLE_EN)[key as keyof typeof SIMPLE_EN];
 return locale === 'es' ? ES[key as keyof typeof EN] : EN[key as keyof typeof EN];
}
