/** Localized copy for the shared Hebra/Obsidian inventory observation surface. */
const EN = {
 details: 'Details', notices: 'Observed valuable items', noNotices: 'No notification intents recorded.', receiptLimit: 'Addon acceptance does not confirm that a notice was displayed.', noticeValue: 'Estimated value', noticeState: 'Notification intent', receipt: 'Addon receipt', noReceipt: 'No receipt', notice_awaiting_price: 'Waiting for a price', notice_skipped: 'Skipped', notice_ready: 'Ready', notice_dispatching: 'Dispatch claimed', notice_processed: 'Processed', noticeNoPrice: 'No price', noticeBelowThreshold: 'Below threshold', noticeClosed: 'Session closed', receipt_pending: 'Awaiting receipt', receipt_received: 'Accepted by addon', receipt_unconfirmed: 'Receipt unconfirmed · may not have been displayed', noticeFailed: 'Failed channels',
 history: 'Saved session', current: 'Current session', refreshHistory: 'Refresh history', loadingHistory: 'Loading saved sessions…', historyFailed: 'Could not load this session. Your recorded data is kept; try again.', title: 'Inventory observations', timeline: 'Timeline', summary: 'Session summary',
 positiveValue: 'Estimated known increases', source: 'Source', nexus: 'Local Nexus · character bags', missing: 'No Nexus inventory source',
 warming_up: 'Waiting for baseline', ready: 'Reading available', stale: 'Reading is old',
 unavailable: 'Reading unavailable', conflict: 'Another Nexus source owns this session',
 connected: 'Game connected', disconnected: 'Game disconnected',
 idle: 'No session', starting: 'Preparing session', active: 'Session active', stopping: 'Finishing session',
 complete: 'Session complete', error: 'Session error · recovery required',
 empty: 'No inventory changes observed yet. A baseline is not an acquisition.',
 noSession: 'Connect a supported local Nexus reader to start an observation session.',
 scope: 'Observed increases and decreases in character bags. Their cause is unknown; changes between samples may be missed.',
 items: 'Item coverage', currencies: 'Currency coverage', covered: 'Complete character bags',
 partial: 'Partial', none: 'No coverage', listed: 'Listed currencies only',
 duration: 'Active duration', observedDuration: 'Covered item duration', quantityChart: 'Observed net item quantity',
 valueChart: 'Estimated net item subtotal', fullValue: 'Estimated net value', coin: 'Observed net coins',
 rate: 'Estimated item subtotal/hour · partial', unavailableRate: 'No eligible rate yet',
 priceBasis: 'Valuation criterion', price: 'Instant sell, net of fees', priceAt: 'Price snapshot', unpriced: 'Items without a price',
 time: 'Observed at', entity: 'Item / currency', quantity: 'Change', before: 'Before', after: 'After',
 increases: 'Increases', decreases: 'Decreases', net: 'Net change', entryValue: 'Estimated value', value: 'Estimated known net item subtotal',
 previous: 'Previous', next: 'Next', page: 'Page', changes: 'Observed changes', entities: 'Items / currencies',
 exportTimeline: 'Export timeline', exportSummary: 'Export summary', exporting: 'Exporting…',
 exported: 'Export saved', exportFailed: 'Could not export. The session is kept; try again.',
 gaps: 'Reading gaps', openGap: 'Ongoing', gapLimit: 'No curve is interpolated across reading gaps.',
 chartWindow: 'Latest 200 committed samples', tableChart: 'Chart data', slots: 'Free character bag slots',
 magicFind: 'Magic Find', manual: 'Manual', verified: 'Verified', unknown: 'Unknown',
 last: 'Last committed reading', noReading: 'No committed reading', baselineRecovery: 'Waiting for a new baseline after a reading gap.',
 disconnect: 'Connection lost', source_stale: 'No recent reader sample', read_failed: 'Reader could not complete the sample', partial_inventory: 'Some bag positions could not be read', context_changed: 'Character or map changed', host_restart: 'Host restarted', storage_unavailable: 'Could not store the reading', unsupported_build: 'Unsupported game build', source_missing: 'Reader source missing', cursor_gap: 'Missing sample', kindItem: 'Item', kindCurrency: 'Currency', pause: 'Observation paused',
} as const;
const ES: Record<keyof typeof EN, string> = {
 details: 'Detalles', notices: 'Objetos valiosos observados', noNotices: 'Sin intentos de aviso guardados.', receiptLimit: 'La aceptación del addon no confirma que el aviso se haya mostrado.', noticeValue: 'Valor estimado', noticeState: 'Intento de aviso', receipt: 'Recepción del addon', noReceipt: 'Sin recepción', notice_awaiting_price: 'Esperando precio', notice_skipped: 'Omitido', notice_ready: 'Preparado', notice_dispatching: 'Envío reclamado', notice_processed: 'Procesado', noticeNoPrice: 'Sin precio', noticeBelowThreshold: 'Bajo el umbral', noticeClosed: 'Sesión terminada', receipt_pending: 'Esperando recepción', receipt_received: 'Aceptado por el addon', receipt_unconfirmed: 'Recepción no confirmada · puede no haberse mostrado', noticeFailed: 'Canales fallidos',
 history: 'Sesión guardada', current: 'Sesión actual', refreshHistory: 'Actualizar historial', loadingHistory: 'Cargando sesiones guardadas…', historyFailed: 'No se pudo cargar esta sesión. Los datos guardados se conservan; vuelve a intentarlo.', title: 'Observaciones del inventario', timeline: 'Cronología', summary: 'Resumen de sesión',
 positiveValue: 'Aumentos conocidos estimados', source: 'Fuente', nexus: 'Nexus local · bolsas del personaje', missing: 'Sin fuente Nexus de inventario',
 warming_up: 'Esperando baseline', ready: 'Lectura disponible', stale: 'Lectura antigua',
 unavailable: 'Lectura no disponible', conflict: 'Otra fuente Nexus posee esta sesión',
 connected: 'Juego conectado', disconnected: 'Juego desconectado',
 idle: 'Sin sesión', starting: 'Preparando sesión', active: 'Sesión activa', stopping: 'Terminando sesión',
 complete: 'Sesión terminada', error: 'Error de sesión · requiere recuperación',
 empty: 'Todavía no se han observado cambios de inventario. Un baseline no es una adquisición.',
 noSession: 'Conecta un lector Nexus local compatible para iniciar una sesión de observación.',
 scope: 'Aumentos y disminuciones observados en las bolsas del personaje. Su causa es desconocida; pueden perderse cambios entre muestras.',
 items: 'Cobertura de objetos', currencies: 'Cobertura de monedas', covered: 'Bolsas del personaje completas',
 partial: 'Parcial', none: 'Sin cobertura', listed: 'Solo monedas enumeradas',
 duration: 'Duración activa', observedDuration: 'Duración cubierta de objetos', quantityChart: 'Cantidad neta observada de objetos',
 valueChart: 'Subtotal neto estimado de objetos', fullValue: 'Valor neto estimado', coin: 'Monedas netas observadas',
 rate: 'Subtotal estimado de objetos/h · parcial', unavailableRate: 'Sin ritmo elegible todavía',
 priceBasis: 'Criterio de valoración', price: 'Venta inmediata, descontadas comisiones', priceAt: 'Precios capturados', unpriced: 'Objetos sin precio',
 time: 'Observado a las', entity: 'Objeto / moneda', quantity: 'Cambio', before: 'Antes', after: 'Después',
 increases: 'Aumentos', decreases: 'Disminuciones', net: 'Cambio neto', entryValue: 'Valor estimado', value: 'Subtotal neto estimado de objetos conocidos',
 previous: 'Anterior', next: 'Siguiente', page: 'Página', changes: 'Cambios observados', entities: 'Objetos / monedas',
 exportTimeline: 'Exportar cronología', exportSummary: 'Exportar resumen', exporting: 'Exportando…',
 exported: 'Exportación guardada', exportFailed: 'No se pudo exportar. La sesión se conserva; vuelve a intentarlo.',
 gaps: 'Huecos de lectura', openGap: 'En curso', gapLimit: 'La curva no interpola los huecos de lectura.',
 chartWindow: 'Últimas 200 muestras guardadas', tableChart: 'Datos de la gráfica', slots: 'Huecos libres en las bolsas del personaje',
 magicFind: 'Hallazgo mágico', manual: 'Manual', verified: 'Verificado', unknown: 'Desconocido',
 last: 'Última lectura guardada', noReading: 'Sin lectura guardada', baselineRecovery: 'Esperando un nuevo baseline tras un hueco de lectura.',
 disconnect: 'Conexión perdida', source_stale: 'Sin muestra reciente del lector', read_failed: 'El lector no pudo completar la muestra', partial_inventory: 'No se pudieron leer algunas posiciones de las bolsas', context_changed: 'Cambio de personaje o mapa', host_restart: 'Host reiniciado', storage_unavailable: 'No se pudo guardar la lectura', unsupported_build: 'Versión del juego no compatible', source_missing: 'Falta la fuente del lector', cursor_gap: 'Falta una muestra', kindItem: 'Objeto', kindCurrency: 'Moneda', pause: 'Observación pausada',
};
export type LiveSessionCopyKey = keyof typeof EN;
export function liveSessionCopy(locale: 'es' | 'en', key: LiveSessionCopyKey): string {
 return locale === 'es' ? ES[key] : EN[key];
}
