/**
 * Regenerates `src/assets/published-base-hashes.ts`: the semantic fingerprint of every Base
 * of every published release plus the working tree.
 *
 * Each release is extracted with `git archive` into a temporary directory and hashed with THAT
 * release's own bundle and the repository's current `baseSemanticHash`, so the table is measured
 * from what was actually shipped rather than transcribed. Run it whenever a Base's content or
 * `contentVersion` changes (a test fails until you do):
 *
 *   node node_modules/jiti/lib/jiti-cli.mjs scripts/generate-published-base-hashes.ts
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, rmSync, symlinkSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

import { baseSemanticHash } from '../src/assets/managed-assets';
import { managedAssetsBundle } from '../src/assets/generic-assets';
import type { PackagedAsset } from '../src/assets/managed-assets-model';

interface Row { assetId: string; locale: string; contentVersion: number; semanticHash: string }

const ROOT = resolve(__dirname, '..');
const OUTPUT = join(ROOT, 'src/assets/published-base-hashes.ts');

function git(...args: string[]): string {
	return execFileSync('git', ['-C', ROOT, ...args], { encoding: 'utf8', maxBuffer: 256 * 1024 * 1024 });
}

function versionKey(tag: string): [number, number, number] { const [a = 0, b = 0, c = 0] = tag.split('.').map(Number); return [a, b, c]; }

async function rowsOf(bundle: PackagedAsset[], hash: (bytes: string) => Promise<string | null>): Promise<Row[]> {
	const rows: Row[] = [];
	for (const asset of bundle) {
		if (asset.kind !== 'base') continue;
		const semanticHash = await hash(asset.bytes);
		if (semanticHash === null) throw new Error(`unhashable base ${asset.id}@${asset.contentVersion}`);
		rows.push({ assetId: asset.id, locale: asset.locale, contentVersion: asset.contentVersion, semanticHash });
	}
	return rows;
}

async function main(): Promise<void> {
	const { createJiti } = await import('jiti');
	const tags = git('tag', '--list').split('\n').filter((tag) => /^\d+\.\d+\.\d+$/u.test(tag))
		.sort((a, b) => { const [x, y] = [versionKey(a), versionKey(b)]; return (x[0] - y[0]) || (x[1] - y[1]) || (x[2] - y[2]); });
	const all: Row[] = [];
	const scratch = mkdtempSync(join(tmpdir(), 'tc-published-'));
	try {
		for (const tag of tags) {
			const dir = join(scratch, tag);
			execFileSync('mkdir', ['-p', dir]);
			execFileSync('sh', ['-c', `git -C "${ROOT}" archive "${tag}" src | tar -x -C "${dir}"`]);
			symlinkSync(join(ROOT, 'node_modules'), join(dir, 'node_modules'));
			const managed = join(dir, 'src/assets/managed-assets.ts');
			if (!existsSync(managed)) continue;
			writeFileSync(managed, `${readFileSync(managed, 'utf8')}\nexport { baseSemanticHash as __bsh };\n`);
			const jiti = createJiti(join(dir, 'x.ts'), { moduleCache: false, fsCache: false });
			const m = await jiti.import<{ __bsh: (c: string) => Promise<string | null> }>(managed);
			const g = await jiti.import<{ managedAssetsBundle: () => Promise<PackagedAsset[]> }>(join(dir, 'src/assets/generic-assets.ts'));
			all.push(...await rowsOf(await g.managedAssetsBundle(), m.__bsh));
		}
	} finally { rmSync(scratch, { recursive: true, force: true }); }
	all.push(...await rowsOf(await managedAssetsBundle(), baseSemanticHash));

	const seen = new Set<string>();
	const rows = all.filter((row) => {
		const key = `${row.assetId}|${row.locale}|${row.contentVersion}|${row.semanticHash}`;
		return seen.has(key) ? false : (seen.add(key), true);
	}).sort((a, b) => a.assetId.localeCompare(b.assetId) || a.locale.localeCompare(b.locale) || a.contentVersion - b.contentVersion
		|| a.semanticHash.localeCompare(b.semanticHash));
	const body = rows.map((row) => `\t{ assetId: '${row.assetId}', locale: '${row.locale}', contentVersion: ${row.contentVersion}, semanticHash: '${row.semanticHash}' },`).join('\n');
	writeFileSync(OUTPUT, `// GENERATED by scripts/generate-published-base-hashes.ts from the release tags (${tags[0]}..${tags.at(-1)}) and the working tree.
// Do not edit by hand: regenerate it when a Base's content or contentVersion changes.
import type { AssetLocale } from './managed-assets-model';

export interface PublishedBaseFingerprint {
	assetId: string;
	locale: AssetLocale;
	contentVersion: number;
	/** \`baseSemanticHash\` of the Base as that release shipped it. */
	semanticHash: string;
}

export const PUBLISHED_BASE_FINGERPRINTS: readonly PublishedBaseFingerprint[] = [
${body}
];
`);
	process.stdout.write(`${rows.length} fingerprints from ${tags.length} tags\n`);
}

void main();
