// GENERATED by scripts/generate-published-base-hashes.ts from the release tags (0.1.5..0.6.15) and the working tree.
// Do not edit by hand: regenerate it when a Base's content or contentVersion changes.
import type { AssetLocale } from './managed-assets-model';

export interface PublishedBaseFingerprint {
	assetId: string;
	locale: AssetLocale;
	contentVersion: number;
	/** `baseSemanticHash` of the Base as that release shipped it. */
	semanticHash: string;
}

export const PUBLISHED_BASE_FINGERPRINTS: readonly PublishedBaseFingerprint[] = [
	{ assetId: 'halloween-base', locale: 'en', contentVersion: 1, semanticHash: 'd87aea46deb03d408bec96be2f663692b243c73eb97926c415d7b3a80c219112' },
	{ assetId: 'halloween-base', locale: 'es', contentVersion: 1, semanticHash: '0013222ca66d074b04e4b4726c3fe0e6ecbd1ec1b56e94aefac8b8c6ff837b9d' },
	{ assetId: 'inventory-base', locale: 'en', contentVersion: 2, semanticHash: '47edb8967c61422a049a1d4e4466a56520470e6de74298b67d56bb194d880473' },
	{ assetId: 'inventory-base', locale: 'en', contentVersion: 2, semanticHash: '8e1408c478abda471ab87afbf074c45d8e5d4e1d3087a444c1514f0288f4b643' },
	{ assetId: 'inventory-base', locale: 'en', contentVersion: 2, semanticHash: 'c4260334714f93b70c9fa30ad97fb19a5175c5e0566d1a9a702786f21f82118e' },
	{ assetId: 'inventory-base', locale: 'en', contentVersion: 4, semanticHash: '205b835f61f0d84cdf113b91e9a0d1c8fba5599f366d485d171f03a70fabcc8f' },
	{ assetId: 'inventory-base', locale: 'en', contentVersion: 5, semanticHash: '2e79bf44634fdedee80583422d3571e00272f12ff33d96c400dc7a2740142bb1' },
	{ assetId: 'inventory-base', locale: 'en', contentVersion: 7, semanticHash: '0cdce6ec4473b0b8dfd6f88a655035282afe9eea90fac46ab0fb8d9a0680f520' },
	{ assetId: 'inventory-base', locale: 'en', contentVersion: 10, semanticHash: '1a7303b3a6c017339dcf79992634babf838d8aff88058e2ef8b38023925bb1c9' },
	{ assetId: 'inventory-base', locale: 'en', contentVersion: 10, semanticHash: 'a7018b35383855432a96021dd631ed38d5262dd386b7b6f05f7bb874eed019b4' },
	{ assetId: 'inventory-base', locale: 'es', contentVersion: 2, semanticHash: '458a999e5e1d233b4bcd15eea33a5826e7a233567d269643972d3e68025f18d1' },
	{ assetId: 'inventory-base', locale: 'es', contentVersion: 2, semanticHash: 'bc712bdd81e9851393a7a415735528ec9d4e409f346edcc158e5e5ec02bebc08' },
	{ assetId: 'inventory-base', locale: 'es', contentVersion: 2, semanticHash: 'fc8c8c15ebb9b6a0dcad5e3d46e7c71b37a1354af3f6801fdfdf022472b69673' },
	{ assetId: 'inventory-base', locale: 'es', contentVersion: 4, semanticHash: 'c9c091afd6752910a3244d94be4f75073136d2823ea14327c5ff6dcc0ef12f87' },
	{ assetId: 'inventory-base', locale: 'es', contentVersion: 5, semanticHash: 'fce9500ccd6ecc126ec3a5c382397ce146db428b7802eb21dc2e1b48869179ed' },
	{ assetId: 'inventory-base', locale: 'es', contentVersion: 7, semanticHash: '5959e6e56bc2ad7b0e384e46f9d1ed3aec9c5536d9e50f487f9b58e638e89c79' },
	{ assetId: 'inventory-base', locale: 'es', contentVersion: 10, semanticHash: '0c4c8e2ac7655b5d2dc3fb0744334a859f342c7b8fc93852b27ebe898cbe19a8' },
	{ assetId: 'inventory-base', locale: 'es', contentVersion: 10, semanticHash: '14be1c1c94122172cb902cb3f41be8232b596d71e65ee2187ce39e40b5ba3e9a' },
	{ assetId: 'materials-base', locale: 'en', contentVersion: 2, semanticHash: '14e04c5e3da79a478aa7cfbaee2a62b92ff430e970cff40e8de83c5799f24362' },
	{ assetId: 'materials-base', locale: 'en', contentVersion: 2, semanticHash: '66a9786389c1d5e484fdef7e41170297fab59b888eefd1d63114d146d8aafc5b' },
	{ assetId: 'materials-base', locale: 'en', contentVersion: 2, semanticHash: '85c34bad01d342f9c4c925c9cfaa61c3b6c308f414a490ec12ee69f13247aaf4' },
	{ assetId: 'materials-base', locale: 'en', contentVersion: 4, semanticHash: '47136b7d478b55596a43ec9b6e48441c7d5e51eca91c1132f79601fcbaaa0ad8' },
	{ assetId: 'materials-base', locale: 'en', contentVersion: 5, semanticHash: '187f8e71512eae7ebd9e0dcb5d92a64f647dd1ce3ca40659201cbc76c5bcd749' },
	{ assetId: 'materials-base', locale: 'en', contentVersion: 7, semanticHash: '523b9834a6f2527bc2faaca174bf1e02fc638e54ee04b34fc0feab8838b44a2c' },
	{ assetId: 'materials-base', locale: 'en', contentVersion: 10, semanticHash: '539a054f7d1668be0a34e7e526ed2c015ab1ace2222bfe5b01b7dc0bf5699202' },
	{ assetId: 'materials-base', locale: 'en', contentVersion: 10, semanticHash: '74f6a5de0e4fc6cc293af4eec75e395787e01b1e8894cc97e1a5be3957904d4e' },
	{ assetId: 'materials-base', locale: 'es', contentVersion: 2, semanticHash: '42451e05516c8e96b132bce3fa745561f1850ea26b831cc07200d39be3d20fce' },
	{ assetId: 'materials-base', locale: 'es', contentVersion: 2, semanticHash: '53eaf9c4bd233c6822a81a844d72f87c99ca9057413d548b30d1a769d7f20f52' },
	{ assetId: 'materials-base', locale: 'es', contentVersion: 2, semanticHash: '6c1e9d432f5e1652907b4a6cb7c31288c4edf1949baa0c674fa972dc9cc40b9b' },
	{ assetId: 'materials-base', locale: 'es', contentVersion: 4, semanticHash: 'fdef8ecc4954483f35e02b40ac1d6cc3b16d84665d83b75b367b753f7008dea9' },
	{ assetId: 'materials-base', locale: 'es', contentVersion: 5, semanticHash: 'a93f280cceae6bc0ed5abeb574e4f7340e41366562edc2b56f6d56b054c642f5' },
	{ assetId: 'materials-base', locale: 'es', contentVersion: 7, semanticHash: '11fd9965ddea11051db823146e129c96e61153057389758f1878631083cf77f5' },
	{ assetId: 'materials-base', locale: 'es', contentVersion: 10, semanticHash: '0fe87447c13685421564b9af074758c04b7078b0c1284e3d0657d5a24bd69bf7' },
	{ assetId: 'materials-base', locale: 'es', contentVersion: 10, semanticHash: 'e882ae64c38c045fc3a3e32a279c6dd0dc4c252fda94eab69ca061ff039e4552' },
	{ assetId: 'session-summaries-base', locale: 'en', contentVersion: 1, semanticHash: '414578cc7fe581a5c8460aab3a469e545f8345be6bb619cfe9340b61c1ebae5e' },
	{ assetId: 'session-summaries-base', locale: 'en', contentVersion: 2, semanticHash: 'bb6e012155b5e34be14ae1d1af54b543aac4c9a15b3d78d0f572a02d955fa532' },
	{ assetId: 'session-summaries-base', locale: 'es', contentVersion: 1, semanticHash: '33f7c54bcf90e531091efac35b0359d0f44adb90d5695e2e68d8963b5594f691' },
	{ assetId: 'session-summaries-base', locale: 'es', contentVersion: 2, semanticHash: '24fa9c5e197e1eb3790636be57ec97d182adf1637a8834159dcc522b17406819' },
	{ assetId: 'sessions-base', locale: 'neutral', contentVersion: 2, semanticHash: '6482732191c7f9c9ef53f140c7c3fa854d1cd88abba06ac8465b5ed4ca73e993' },
	{ assetId: 'wallet-base', locale: 'en', contentVersion: 1, semanticHash: '9b8b18ed917fe5cadcb6dbc9bdf34eb75c3f8941ef7f349561c6a319531e3ba6' },
	{ assetId: 'wallet-base', locale: 'es', contentVersion: 1, semanticHash: 'a0aff9de867534b692e79a0ce0381ff77b78630f82945471a9af9d3cc738ca05' },
];
